import unittest
from cobol_append import get_full_cobol_code, get_dat_content

owner = 'domenicodegioia'
repo = 'cobolProject2'
path = 'mainprogram.cbl'

output_full_code = '''IDENTIFICATION DIVISION.
PROGRAM-ID. MAINPROGRAM.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION.
    PERFORM INITIALIZE-SYSTEM
    PERFORM MENU-SELECTION
    STOP RUN.

INITIALIZE-SYSTEM.
    DISPLAY "Welcome to the Public Administration System".

MENU-SELECTION.
    DISPLAY "Choose an option:"
    DISPLAY "1. Manage Taxes"
    DISPLAY "2. Manage Contributions"
    DISPLAY "3. Manage Pensions"
    ACCEPT USER-INPUT
    EVALUATE USER-INPUT
        WHEN "1" PERFORM TAX-OPERATIONS
        WHEN "2" PERFORM CONTRIBUTION-OPERATIONS
        WHEN "3" PERFORM PENSION-OPERATIONS
        WHEN OTHER DISPLAY "Invalid option".
    END-EVALUATE.

TAX-OPERATIONS.
    CALL "TAXMODULE" USING USER-STRUCTURE.

CONTRIBUTION-OPERATIONS.
    CALL "CONTRIBUTIONMODULE" USING USER-STRUCTURE.

PENSION-OPERATIONS.
    CALL "PENSIONMODULE" USING USER-STRUCTURE.
* CALL TAXMODULE
IDENTIFICATION DIVISION.
PROGRAM-ID. TAXMODULE.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION USING USER-STRUCTURE.
    DISPLAY "Managing Taxes"
    DISPLAY "Enter your tax details"
    PERFORM CALCULATE-TAX
    PERFORM DISPLAY-TAX-INFO
    STOP RUN.

CALCULATE-TAX.
    COMPUTE USER-TAX = USER-INCOME * 0.2.

DISPLAY-TAX-INFO.
    DISPLAY "Your calculated tax is: " USER-TAX.
* CALL CONTRIBUTIONMODULE
IDENTIFICATION DIVISION.
PROGRAM-ID. CONTRIBUTIONMODULE.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION USING USER-STRUCTURE.
    DISPLAY "Managing Contributions"
    DISPLAY "Enter your contribution amount:"
    ACCEPT USER-CONTRIBUTION
    PERFORM ADD-CONTRIBUTION
    PERFORM DISPLAY-CONTRIBUTION-INFO
    STOP RUN.

ADD-CONTRIBUTION.
    ADD USER-CONTRIBUTION TO USER-TOTAL-CONTRIBUTIONS.

DISPLAY-CONTRIBUTION-INFO.
    DISPLAY "Your total contributions are: " USER-TOTAL-CONTRIBUTIONS.
* CALL PENSIONMODULE
IDENTIFICATION DIVISION.
PROGRAM-ID. PENSIONMODULE.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION USING USER-STRUCTURE.
    DISPLAY "Managing Pension"
    PERFORM CALCULATE-PENSION
    PERFORM DISPLAY-PENSION-INFO
    STOP RUN.

CALCULATE-PENSION.
    COMPUTE USER-PENSION = (USER-CONTRIBUTIONS * 0.6).

DISPLAY-PENSION-INFO.
    DISPLAY "Your pension is: " USER-PENSION.'''
output_dat_content = '''userdata.dat
John Doe       50000.00   12000.00   10000.00  18000.00  2000.00
Jane Smith     60000.00   15000.00   12000.00  20000.00  3000.00
Paul Brown     45000.00    8000.00    9000.00  16000.00  1500.00
Lisa White     70000.00   20000.00   14000.00  22000.00  4000.00
Mark Johnson   55000.00   11000.00   11000.00  19000.00  2500.00
Emily Clark    48000.00    9000.00    9500.00  17000.00  1700.00
David Lee      52000.00   13000.00   10500.00  18500.00  2800.00
Sophia Wilson  62000.00   16000.00   12500.00  21000.00  3200.00
Michael Davis  47000.00    8500.00    9200.00  16500.00  1600.00
'''

class TestUtilsFunctions(unittest.TestCase):

    def test_git_utils(self):
        self.assertEqual(get_full_cobol_code(owner, repo, path), output_full_code)
        self.assertEqual(get_dat_content(owner, repo), output_dat_content)

if __name__ == '__main__':
    unittest.main()