import unittest
from cobol_to_ast import ASTGenerator
import re

input_cobol_code = '''IDENTIFICATION DIVISION.
PROGRAM-ID. MAINPROGRAM.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION.
    PERFORM INITIALIZE-SYSTEM
    PERFORM MENU-SELECTION
    STOP RUN.

INITIALIZE-SYSTEM.
    DISPLAY "Welcome to the Public Administration System".

MENU-SELECTION.
    DISPLAY "Choose an option:"
    DISPLAY "1. Manage Taxes"
    DISPLAY "2. Manage Contributions"
    DISPLAY "3. Manage Pensions"
    ACCEPT USER-INPUT
    EVALUATE USER-INPUT
        WHEN "1" PERFORM TAX-OPERATIONS
        WHEN "2" PERFORM CONTRIBUTION-OPERATIONS
        WHEN "3" PERFORM PENSION-OPERATIONS
        WHEN OTHER DISPLAY "Invalid option".
    END-EVALUATE.

TAX-OPERATIONS.
    CALL "TAXMODULE" USING USER-STRUCTURE.

CONTRIBUTION-OPERATIONS.
    CALL "CONTRIBUTIONMODULE" USING USER-STRUCTURE.

PENSION-OPERATIONS.
    CALL "PENSIONMODULE" USING USER-STRUCTURE.
* CALL TAXMODULE
IDENTIFICATION DIVISION.
PROGRAM-ID. TAXMODULE.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION USING USER-STRUCTURE.
    DISPLAY "Managing Taxes"
    DISPLAY "Enter your tax details"
    PERFORM CALCULATE-TAX
    PERFORM DISPLAY-TAX-INFO
    STOP RUN.

CALCULATE-TAX.
    COMPUTE USER-TAX = USER-INCOME * 0.2.

DISPLAY-TAX-INFO.
    DISPLAY "Your calculated tax is: " USER-TAX.
* CALL CONTRIBUTIONMODULE
IDENTIFICATION DIVISION.
PROGRAM-ID. CONTRIBUTIONMODULE.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION USING USER-STRUCTURE.
    DISPLAY "Managing Contributions"
    DISPLAY "Enter your contribution amount:"
    ACCEPT USER-CONTRIBUTION
    PERFORM ADD-CONTRIBUTION
    PERFORM DISPLAY-CONTRIBUTION-INFO
    STOP RUN.

ADD-CONTRIBUTION.
    ADD USER-CONTRIBUTION TO USER-TOTAL-CONTRIBUTIONS.

DISPLAY-CONTRIBUTION-INFO.
    DISPLAY "Your total contributions are: " USER-TOTAL-CONTRIBUTIONS.
* CALL PENSIONMODULE
IDENTIFICATION DIVISION.
PROGRAM-ID. PENSIONMODULE.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "USER-STRUCTURE.CPY".
PROCEDURE DIVISION USING USER-STRUCTURE.
    DISPLAY "Managing Pension"
    PERFORM CALCULATE-PENSION
    PERFORM DISPLAY-PENSION-INFO
    STOP RUN.

CALCULATE-PENSION.
    COMPUTE USER-PENSION = (USER-CONTRIBUTIONS * 0.6).

DISPLAY-PENSION-INFO.
    DISPLAY "Your pension is: " USER-PENSION.'''
expected_output_ast = '(startRule (compilationUnit (programUnit (identificationDivision IDENTIFICATION DIVISION .\n (programIdParagraph PROGRAM-ID .  (programName (cobolWord MAINPROGRAM)) .\n)) (environmentDivision ENVIRONMENT DIVISION .\n) (dataDivision DATA DIVISION .\n (dataDivisionSection (workingStorageSection WORKING-STORAGE SECTION .\n))))) COPY "USER-STRUCTURE.CPY" .\n PROCEDURE DIVISION .\n     PERFORM INITIALIZE-SYSTEM PERFORM MENU-SELECTION STOP RUN .\n\n INITIALIZE-SYSTEM .\n     DISPLAY "Welcome to the Public Administration System" .\n\n MENU-SELECTION .\n     DISPLAY "Choose an option:" DISPLAY "1. Manage Taxes" DISPLAY "2. Manage Contributions" DISPLAY "3. Manage Pensions" ACCEPT USER-INPUT EVALUATE USER-INPUT WHEN "1" PERFORM TAX-OPERATIONS WHEN "2" PERFORM CONTRIBUTION-OPERATIONS WHEN "3" PERFORM PENSION-OPERATIONS WHEN OTHER DISPLAY "Invalid option" .\n     END-EVALUATE .\n\n TAX-OPERATIONS .\n     CALL "TAXMODULE" USING USER-STRUCTURE .\n\n CONTRIBUTION-OPERATIONS .\n     CALL "CONTRIBUTIONMODULE" USING USER-STRUCTURE .\n\n PENSION-OPERATIONS .\n     CALL "PENSIONMODULE" USING USER-STRUCTURE .\n * CALL TAXMODULE IDENTIFICATION DIVISION .\n PROGRAM-ID .  TAXMODULE .\n ENVIRONMENT DIVISION .\n DATA DIVISION .\n WORKING-STORAGE SECTION .\n COPY "USER-STRUCTURE.CPY" .\n PROCEDURE DIVISION USING USER-STRUCTURE .\n     DISPLAY "Managing Taxes" DISPLAY "Enter your tax details" PERFORM CALCULATE-TAX PERFORM DISPLAY-TAX-INFO STOP RUN .\n\n CALCULATE-TAX .\n     COMPUTE USER-TAX = USER-INCOME * 0.2 .\n\n DISPLAY-TAX-INFO .\n     DISPLAY "Your calculated tax is: " USER-TAX .\n * CALL CONTRIBUTIONMODULE IDENTIFICATION DIVISION .\n PROGRAM-ID .  CONTRIBUTIONMODULE .\n ENVIRONMENT DIVISION .\n DATA DIVISION .\n WORKING-STORAGE SECTION .\n COPY "USER-STRUCTURE.CPY" .\n PROCEDURE DIVISION USING USER-STRUCTURE .\n     DISPLAY "Managing Contributions" DISPLAY "Enter your contribution amount:" ACCEPT USER-CONTRIBUTION PERFORM ADD-CONTRIBUTION PERFORM DISPLAY-CONTRIBUTION-INFO STOP RUN .\n\n ADD-CONTRIBUTION .\n     ADD USER-CONTRIBUTION TO USER-TOTAL-CONTRIBUTIONS .\n\n DISPLAY-CONTRIBUTION-INFO .\n     DISPLAY "Your total contributions are: " USER-TOTAL-CONTRIBUTIONS .\n * CALL PENSIONMODULE IDENTIFICATION DIVISION .\n PROGRAM-ID .  PENSIONMODULE .\n ENVIRONMENT DIVISION .\n DATA DIVISION .\n WORKING-STORAGE SECTION .\n COPY "USER-STRUCTURE.CPY" .\n PROCEDURE DIVISION USING USER-STRUCTURE .\n     DISPLAY "Managing Pension" PERFORM CALCULATE-PENSION PERFORM DISPLAY-PENSION-INFO STOP RUN .\n\n CALCULATE-PENSION .\n     COMPUTE USER-PENSION = ( USER-CONTRIBUTIONS * 0.6 ) .\n\n DISPLAY-PENSION-INFO .\n     DISPLAY "Your pension is: " USER-PENSION .)'


class TestUtilsFunctions(unittest.TestCase):

    def test_git_utils(self):
        output_ast = ASTGenerator(input_cobol_code)
        self.assertEqual(re.sub(r'\s+', ' ', output_ast).strip(), re.sub(r'\s+', ' ', output_ast).strip())


if __name__ == '__main__':
    unittest.main()